---
- name: Add app group
  ansible.builtin.group:
    name: tmf
    state: present

- name: Add app user
  ansible.builtin.user:
    name: {{ username }}
    password: {{ password }}
    expires: -1
    group: tmf
    append: yes
    shell: /bin/bash
    state: present





