---
- name: Setup App and User
  hosts: localhost
  connection: local
  environment:
    ORIGIN_URL: {{ url }}

  tasks:
    - name: Setup User
      ansible.builtin.include_role:
        name: base_image
      vars:
        username: {{ user }}
        password: {{ password }}

    - name: Setup App
      ansible.builtin.include_role:
        name: tmf_app
